pre_bump_hooks = [
	# pre 1.0.0 the 0.X.0 is our 'major' version
  # NOTE: version.* expansion is not available in regular cocogitto. I (zaucy) am using a fork
	"buildozer 'set version {{version}}' 'set compatibility_level {{version.minor}}' //MODULE.bazel:%module",
]

post_bump_hooks = [
	"git push",
	"git push origin {{version}}",
	"gh release create {{version}} --generate-notes --latest -t {{version}} --verify-tag",
]